### ISSUE TITLE
Connection to PO3 not working with 2.2.7

### ISSUE THREAD

**Issue by Frasprite** [iHealthDeviceLabs/iHealthDeviceLabs-Android#1]
Hi,

BePATIENT DEV team here.
We are current working with v2.2.7 of your **Android SDK**.
Everything is working fine, except for the connection to PO3 devices.
When we use:
```
int type = iHealthDevicesManager.DISCOVERY_PO3;
iHealthDevicesManager.getInstance().startDiscovery(type);
```
scanning of PO3 devices works, but is impossible to connect and use it.
This is the stacktrace obtained after clicking on chosen device from list:
```
06-02 15:14:52.594 17305-17362/com.example.devicelibtest W/BluetoothGatt: Unhandled exception in callback
                                                                          java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
                                                                              at com.ihealth.communication.manager.iHealthDevicesManager.u(Unknown Source)
                                                                              at com.ihealth.communication.manager.f.onCharacteristicRead(Unknown Source)
                                                                              at com.ihealth.communication.base.ble.AndroidBle.onCharacteristicRead(Unknown Source)
                                                                              at com.ihealth.ble.Ble$2.onCharacteristicRead(Ble.java:121)
                                                                              at android.bluetooth.BluetoothGatt$1.onCharacteristicRead(BluetoothGatt.java:356)
                                                                              at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:249)
                                                                              at android.os.Binder.execTransact(Binder.java:446)
```

This issue is fired up when testing on **Android** devices with **Lollipop** (v21 or v22).

Can you please help us with this issue?

Regards,
BePATIENT DEV team

**Comment by ivl** [comment]
I have the same issue with HS4
06-07 12:01:21.791 6088-9006/com.example.devicelibtest W/BluetoothGatt: Unhandled exception in callback
                                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
                                                                            at com.ihealth.communication.manager.iHealthDevicesManager.u(Unknown Source)
                                                                            at com.ihealth.communication.manager.f.onCharacteristicRead(Unknown Source)
                                                                            at com.ihealth.communication.base.ble.AndroidBle.onCharacteristicRead(Unknown Source)
                                                                            at com.ihealth.ble.Ble$2.onCharacteristicRead(Ble.java:121)
                                                                            at android.bluetooth.BluetoothGatt$1.onCharacteristicRead(BluetoothGatt.java:403)
                                                                            at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:249)
                                                                            at android.os.Binder.execTransact(Binder.java:453)
06-07 12:01:50.211 6088-6088/com.example.devicelibtest V/ActivityThread: updateVisibility : ActivityRecord{eb4516 token=android.os.BinderProxy@f6f3985 {com.example.devicelibtest/com.ihealth.main.MainActivity}} show : true

**Comment by acheb** [comment]
PLEASE. is there any apk androik to reset an IHealth AM3 whose account has been lost??\
Thanks in advanced

**Comment by zhaoyongguang** [comment]
@Frasprite @ivl 
Bug fix, update 2.2.8
Thanks for your feedback.

**Comment by acheb** [comment]
Where can I get that and how is supposed to do the pairing.
Thanks in advanced

2016-06-08 5:27 GMT-04:00 zhaoyongguang <notifications@github.com>:

**Comment by jzhw0130** [comment]
@acheb 
You can reset an iHealth AM3 by calling the Api (AM3Control): public void reset(int id);
id = 0xFFFFFFFF

You can pair an iHealth AM3 with your account by calling Api(AM3Control):public void setUserId(int id)
id = your user ID

**Comment by Frasprite** [comment]
@acheb 
You should have open a new issue (or whatever) for your problem and get your answer there.
Your issue is not related to mine and this can create some misunderstood for future readers.
