### ISSUE TITLE
NPE when connected device is moved out of connection reach

### ISSUE THREAD

**Issue by SiimKinks** [iHealthDeviceLabs/iHealthDeviceLabs-Android#20]
I am consistently getting the following NullPointerException when connected AM4 device is moved out of connection reach.

<pre>
W/BluetoothGatt: Unhandled exception in callback
       java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	   at com.ihealth.communication.manager.iHealthDevicesManager.b(Unknown Source)
	   at com.ihealth.communication.manager.a.onConnectionStateChange(Unknown Source)
	   at com.ihealth.communication.manager.e.onConnectionStateChange(Unknown Source)
	   at com.ihealth.communication.base.ble.AndroidBle.onConnectionStateChange(Unknown Source)
	   at com.ihealth.ble.Ble.commandCheckReconnectDevice(Ble.java:321)
	   at com.ihealth.ble.Ble.access$8(Ble.java:283)
	   at com.ihealth.ble.Ble$2.onConnectionStateChange(Ble.java:115)
	   at android.bluetooth.BluetoothGatt$1.onClientConnectionState(BluetoothGatt.java:181)
	   at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:70)
	   at android.os.Binder.execTransact(Binder.java:446)
</pre>

Device OS: Android 5.1.1
Lib versions used: 
* iHealthLibrary_2.3.0.jar
* iHealthLibrary_2.3.0.22.jar

## Steps to reproduce ##

* While AM4 device in range init iHealthDevicesManager:
```java
iHealthDevicesManager manager = iHealthDevicesManager.getInstance();
manager.init(context);
manager.registerClientCallback(devicesCallback);
manager.sdkUserInAuthor(context, userName, clientId, clientSecret, callbackId);
```
* Scan devices
```java
manager.startDiscovery(DISCOVERY_AM4);
```
* Wait for scan results and connect to scanned device:

```java
devicesManager.connectDevice(userName, mac); // returns true
```

* Wait for device state change to `DEVICE_STATE_CONNECTED` in the `onDeviceConnectionStateChange` callback and get control:

```java
Am4Control control = manager.getAm4Control(mac);
```

* Take device far enough to be out of connection reach
* Wait for NPE to happen.

Also thanks to NPE `onDeviceConnectionStateChange` callback method does not get notified of the `DEVICE_STATE_DISCONNECTED` state.

Stacktrace before NPE:
<pre>
09-26 16:54:03.482 1485-1571/com.android.bluetooth W/bt-btif: bta_gattc_conn_cback() - cif=3 connected=0 conn_id=3 reason=0x0008
09-26 16:54:03.483 1485-1571/com.android.bluetooth W/bt-btif: bta_gattc_conn_cback() - cif=4 connected=0 conn_id=4 reason=0x0008
09-26 16:54:03.483 1485-1571/com.android.bluetooth W/bt-btif: bta_gattc_conn_cback() - cif=5 connected=0 conn_id=5 reason=0x0008
09-26 16:54:03.483 1485-1571/com.android.bluetooth W/bt-btif: bta_gattc_conn_cback() - cif=6 connected=0 conn_id=6 reason=0x0008
09-26 16:54:03.483 1485-1571/com.android.bluetooth E/bt-btm: btm_sec_disconnected - Clearing Pending flag
09-26 16:54:03.484 1485-1559/com.android.bluetooth D/BtGatt.GattService: onDisconnected() - clientIf=6, connId=6, address=00:4D:32:07:DE:67
09-26 16:54:03.487 26528-26545/com.sentab.gdd D/BluetoothGatt: onClientConnectionState() - status=8 clientIf=6 device=00:4D:32:07:DE:67
09-26 16:54:03.487 26528-26545/com.sentab.gdd E/Runtime_ble: ble connection mac:00:4D:32:07:DE:67 --- status:8 --- newState:0
09-26 16:54:03.488 26528-26545/com.sentab.gdd I/Runtime_ble: BluetoothGatt Status Error:00:4D:32:07:DE:67
09-26 16:54:03.488 26528-26545/com.sentab.gdd I/Runtime_ble: DisConnection Success
09-26 16:54:03.989 26528-26545/com.sentab.gdd D/BluetoothGatt: cancelOpen() - device: 00:4D:32:07:DE:67
09-26 16:54:03.993 1485-1509/com.android.bluetooth D/BtGatt.GattService: clientDisconnect() - address=00:4D:32:07:DE:67, connId=null
09-26 16:54:03.993 1485-1571/com.android.bluetooth E/bt-btif: No such connection need to be cancelled
09-26 16:54:03.994 1485-1571/com.android.bluetooth E/bt-btif: Do not find the bg connection mask for the remote device
09-26 16:54:03.994 26528-26545/com.sentab.gdd D/BluetoothGatt: close()
09-26 16:54:03.994 26528-26545/com.sentab.gdd D/BluetoothGatt: unregisterApp() - mClientIf=6
09-26 16:54:03.998 1485-1508/com.android.bluetooth D/BtGatt.GattService: unregisterClient() - clientIf=6
09-26 16:54:04.024 26528-26545/com.sentab.gdd W/BluetoothGatt: Unhandled exception in callback
	       java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
		   at com.ihealth.communication.manager.iHealthDevicesManager.b(Unknown Source)
		   at com.ihealth.communication.manager.a.onConnectionStateChange(Unknown Source)
		   at com.ihealth.communication.manager.e.onConnectionStateChange(Unknown Source)
		   at com.ihealth.communication.base.ble.AndroidBle.onConnectionStateChange(Unknown Source)
		   at com.ihealth.ble.Ble.commandCheckReconnectDevice(Ble.java:321)
		   at com.ihealth.ble.Ble.access$8(Ble.java:283)
		   at com.ihealth.ble.Ble$2.onConnectionStateChange(Ble.java:115)
		   at android.bluetooth.BluetoothGatt$1.onClientConnectionState(BluetoothGatt.java:181)
		   at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:70)
		   at android.os.Binder.execTransact(Binder.java:446)
</pre>

**Comment by jzhw0130** [comment]
@SiimKinks 
Please try the beta version, 2.3.0.25, thanks
[iHealthLibrary_2.3.0.25.jar.zip](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/494412/iHealthLibrary_2.3.0.25.jar.zip)

**Comment by SiimKinks** [comment]
@jzhw0130 
I tried version 2.3.0.25 and now for some reason my build is not compiling. I don't know if it's my project setup or some bytes in the lib do not suit to the dex process or whats up. It is compiling with the previous versions tho, but if I change to the provided one I get the following stacktrace:
(Note: I am clean building, syncing gradle files, restarting AS, compiling from the command line and doing all that)

<pre>
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithDexForDevelopDebug'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.
ProcessException: Return code 1 for dex process
        at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:54)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:158)
        at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:173)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more
Caused by: com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return cod
e 1 for dex process
        at com.android.build.gradle.internal.transforms.DexTransform.transform(DexTransform.java:443)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:178)
        at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:174)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:156)
        ... 22 more
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
        at com.android.ide.common.internal.WaitableExecutor.waitForTasksWithQuickFail(WaitableExecutor.java:147)
        at com.android.build.gradle.internal.transforms.DexTransform.transform(DexTransform.java:397)
        ... 25 more
Caused by: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
        at com.android.build.gradle.internal.transforms.DexTransform$PreDexTask.lambda$call$0(DexTransform.java:536)
        at com.android.build.gradle.internal.transforms.DexTransform$PreDexTask$$Lambda$381/1177091763.apply(Unknown Source)
        at com.android.builder.internal.utils.FileCache$1.getOrCreateFile(FileCache.java:59)
        at com.android.build.gradle.internal.transforms.DexTransform$PreDexTask.call(DexTransform.java:518)
        at com.android.build.gradle.internal.transforms.DexTransform$PreDexTask.call(DexTransform.java:447)
Caused by: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
        at com.android.builder.core.DexByteCodeConverter.dexInProcess(DexByteCodeConverter.java:179)
        at com.android.builder.core.DexByteCodeConverter.runDexer(DexByteCodeConverter.java:157)
        at com.android.builder.core.AndroidBuilder.preDexLibraryNoCache(AndroidBuilder.java:1549)
        at com.android.builder.core.AndroidBuilder.preDexLibrary(AndroidBuilder.java:1505)
        at com.android.build.gradle.internal.transforms.DexTransform$PreDexTask.lambda$call$0(DexTransform.java:526)
        ... 4 more
Caused by: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process
        at com.android.builder.core.DexByteCodeConverter.dexInProcess(DexByteCodeConverter.java:177)
        ... 8 more
Caused by: com.android.ide.common.process.ProcessException: Return code 1 for dex process
        at com.android.builder.internal.compiler.DexWrapper$DexProcessResult.assertNormalExitValue(DexWrapper.java:116)
        at com.android.builder.core.DexByteCodeConverter.lambda$dexInProcess$0(DexByteCodeConverter.java:174)
        at com.android.builder.core.DexByteCodeConverter$$Lambda$390/642804018.call(Unknown Source)
</pre>

**Comment by jzhw0130** [comment]
@SiimKinks 
2.3.0.25 works well with our demo, could you try our demo?

[Android_SDK_2.3.0.25.zip](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/495183/Android_SDK_2.3.0.25.zip)

**Comment by SiimKinks** [comment]
@jzhw0130 
I get the same error with your demo when I change Android plugin to 2.2.0; gradle wrapper to 2.14.1; build tools version to 23.0.3 and add debug shrinking by updating app build.gradle with the following build type:

```
debug {
    minifyEnabled true
    useProguard false
    proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
}
```
Also I added the following line to proguard-rules.pro: 
`-ignorewarnings`

**Comment by jzhw0130** [comment]
@SiimKinks 
Our demo did not work for you??    It is strange..

Please try the new version, thanks

[iHealthLibrary_2.3.0.26.jar.zip](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/495592/iHealthLibrary_2.3.0.26.jar.zip)

**Comment by jzhw0130** [comment]
@SiimKinks 
Environment:
Android plugin 2.2, cradle wrapper version 2.14.1; build tools version version 23.0.3.
The same with you.

**Comment by SiimKinks** [comment]
Same problem persists with the new version also. Problem becomes apparent if one would enable proguard. In my case I have the ["new shrinker"](http://tools.android.com/tech-docs/new-build-system/built-in-shrinker) enabled on my debug build.
Interesting fact is that with your SDK latest stable version (2.3.0) this problem does not occur.

Below is your demo project module level build.gradle file that produces this problem:
(Note: disabling shrinker is not an option in my case)

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "com.ihealth.sdk"
        minSdkVersion 14
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        debug {
            minifyEnabled true
            useProguard false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile files('libs/d2xx.jar')
    compile files('libs/iHealthLibrary_2.3.0.25.jar')
    compile files('libs/pl2303driver.jar')
    compile files('libs/smartlinklib3.6.4_product.jar')
}
```

**Comment by jzhw0130** [comment]
@SiimKinks 
With the configuration of  build.gradle, what's the context of proguard?

Could you send me our demo you changed to produce the problem?

Thanks!

**Comment by jzhw0130** [comment]
@SiimKinks 
buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

Configuration above work well for you or not?

**Comment by SiimKinks** [comment]
@jzhw0130 
As I mentioned earlier, turning shrinking/proguard off will not suit for my project.
So, your mentioned solution works but it doesn't fit for my project needs.

I suspect that your jar building has changed somehow and your proguard is stripping some required information out.

Here is your demo project that produces problem:
[Android_SDK_2.3.0.25.zip](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/495958/Android_SDK_2.3.0.25.zip)

**Comment by jzhw0130** [comment]
@SiimKinks 

Try again, thanks
[iHealthLibrary_2.3.0.25.jar.zip](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/497638/iHealthLibrary_2.3.0.25.jar.zip)

**Comment by SiimKinks** [comment]
@jzhw0130 
Now it builds and also the SDK notifies when the device is disconnected, thanks.

**Comment by jzhw0130** [comment]
@SiimKinks 
Good news.

**Comment by niqt** [comment]
I have a null pointer exception with last sdk and demo app (lib 2.3.1)
at com.ihealth.communication.manager.iHealthDevicesManager.init(Unknown Source)
                                                                   at com.ihealth.sdk.MainActivity.onCreate(MainActivity.java:240)

**Comment by jzhw0130** [comment]
@niqt 

Could you send the crash log from logcat?

Thanks

**Comment by niqt** [comment]
01-09 14:21:39.711 26627-26627/? I/art: Late-enabling -Xcheck:jni
01-09 14:21:39.733 26627-26633/? I/art: Debugger is no longer active
01-09 14:21:39.751 26627-26627/? I/InstantRun: Instant Run Runtime started. Android package is com.ihealth.sdk, real application class is null.
01-09 14:21:40.164 26627-26627/? E/MainActivity: Model:Nexus 5 api:23 version:6.0.1
01-09 14:21:40.174 26627-26627/? W/Runtime_iHealthDM: iHealthLibrary Version:ASDK_2.3.1
01-09 14:21:40.176 26627-26627/? D/AndroidRuntime: Shutting down VM
01-09 14:21:40.177 26627-26627/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.ihealth.sdk, PID: 26627
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ihealth.sdk/com.ihealth.sdk.MainActivity}: java.lang.NullPointerException: Attempt to get length of null array
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                    Caused by: java.lang.NullPointerException: Attempt to get length of null array
                                                       at com.ihealth.communication.utils.Logger.a(Unknown Source)
                                                       at com.ihealth.communication.utils.Logger.a(Unknown Source)
                                                       at com.ihealth.communication.utils.Logger.w(Unknown Source)
                                                       at com.ihealth.communication.utils.Log.w(Unknown Source)
                                                       at com.ihealth.communication.manager.iHealthDevicesManager.init(Unknown Source)
                                                       at com.ihealth.sdk.MainActivity.onCreate(MainActivity.java:240)
                                                       at android.app.Activity.performCreate(Activity.java:6251)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by jzhw0130** [comment]
@niqt 

Please try the new version, thanks

[iHealthLibrary_2.3.1.16.jar.zip](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/693581/iHealthLibrary_2.3.1.16.jar.zip)

**Comment by niqt** [comment]
With it seems ok! In 2 days i'll try with all my devices

**Comment by qqskim** [comment]
ok

**Comment by niqt** [comment]
OT: will be possible in future use directly C++/C to connect the device?

**Comment by qqskim** [comment]
Not support now. Maybe ok in future.
