### ISSUE TITLE
JSONException From offline measurement of BP5 device

### ISSUE THREAD

**Issue by manikavi** [iHealthDeviceLabs/iHealthDeviceLabs-Android#31]
Hi Jing,
     I used iHealthLibrary_2.3.0.26_log.jar.zip library in my project ,Getting  **JSONException** ,Please check

```
10-04 19:15:02.189 4668-4668/com.bp5.app I/Bp5: mac: 8CDE5208B6E5
10-04 19:15:02.189 4668-4668/com.bp5.app I/Bp5: deviceType: BP5
10-04 19:15:02.189 4668-4668/com.bp5.app I/Bp5: action: offlinestatus
10-04 19:15:02.189 4668-4668/com.bp5.app I/Bp5: message: {"offlinestatus":true}
10-04 19:15:02.198 4668-7934/com.bp5.app I/Runtime_BtCommThread: read:A008000AA14001010000ED
10-04 19:15:02.206 4668-4668/com.bp5.app I/Bp5: MSG.WHAT 101
10-04 19:15:02.206 4668-4668/com.bp5.app I/Bp5:  HANDLER_MESSAGE isEnableoffline: true
10-04 19:15:02.207 4668-4668/com.bp5.app I/Bp5: mac: 8CDE5208B6E5
10-04 19:15:02.207 4668-4668/com.bp5.app I/Bp5: deviceType: BP5
10-04 19:15:02.207 4668-4668/com.bp5.app I/Bp5: action: offlinenum
10-04 19:15:02.207 4668-4668/com.bp5.app I/Bp5: message: {"type":"BP5","num":1}
10-04 19:15:02.208 4668-4668/com.bp5.app I/Bp5: MSG.WHAT 104
10-04 19:15:02.208 4668-4668/com.bp5.app I/Bp5: HANDLER_OFFLINE_COUNT 1
10-04 19:15:02.215 4668-4668/com.bp5.app I/Bp5: deviceMac :  8CDE5208B6E5
10-04 19:15:02.215 4668-4668/com.bp5.app I/Bp5: bp5Control not is null
10-04 19:15:02.215 4668-4668/com.bp5.app I/Runtime_BtCommThread: write:B007000BA141010000EE
10-04 19:15:02.322 4668-7934/com.bp5.app I/Runtime_BtCommThread: read:A00E000CA1410100100A04130D243B4AD6
10-04 19:15:02.828 4668-4668/com.bp5.app I/Bp5: mac: 8CDE5208B6E5
10-04 19:15:02.829 4668-4668/com.bp5.app I/Bp5: deviceType: BP5
10-04 19:15:02.829 4668-4668/com.bp5.app I/Bp5: action: historicaldata_bp
10-04 19:15:02.829 4668-4668/com.bp5.app I/Bp5: message: {"data":[{"date":"2016-10-4 19:13:00","highpressure":95,"lowpressure":59,"heartrate":74,"arrhythmia":false,"hsd":false,"dataID":"1EF21B474917AA5FEBCE95540357135A"}]}
10-04 19:15:02.829 4668-4668/com.bp5.app I/Bp5: mac: 8CDE5208B6E5
10-04 19:15:02.829 4668-4668/com.bp5.app I/Bp5: deviceType: BP5
10-04 19:15:02.829 4668-4668/com.bp5.app I/Bp5: action: historicaldata_bp
10-04 19:15:02.829 4668-4668/com.bp5.app I/Bp5: message: {"data":[{"date":"2016-10-4 19:13:00","highpressure":95,"lowpressure":59,"heartrate":74,"arrhythmia":false,"hsd":false,"dataID":"1EF21B474917AA5FEBCE95540357135A"}]}
10-04 19:15:02.829 4668-4668/com.bp5.app I/Bp5: MSG.WHAT 103
10-04 19:15:02.830 4668-4668/com.bp5.app I/array: array [{"date":"2016-10-4 19:13:00","highpressure":95,"lowpressure":59,"heartrate":74,"arrhythmia":false,"hsd":false,"dataID":"1EF21B474917AA5FEBCE95540357135A"}]
10-04 19:15:02.837 4668-4668/com.bp5.app W/System.err: org.json.JSONException: No value for wave
10-04 19:15:02.839 4668-4668/com.bp5.app W/System.err:     at org.json.JSONObject.get(JSONObject.java:389)
10-04 19:15:02.839 4668-4668/com.bp5.app W/System.err:     at org.json.JSONObject.getString(JSONObject.java:550)
10-04 19:15:02.839 4668-4668/com.bp5.app W/System.err:     at com.chronicwatch.app.patient.ihealth.BP5$3.handleMessage(BP5.java:480)
10-04 19:15:02.839 4668-4668/com.bp5.app W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-04 19:15:02.839 4668-4668/com.bp5.app W/System.err:     at android.os.Looper.loop(Looper.java:135)
10-04 19:15:02.839 4668-4668/com.bp5.app W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5343)
10-04 19:15:02.839 4668-4668/com.bp5.app W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
10-04 19:15:02.839 4668-4668/com.bp5.app W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
10-04 19:15:02.839 4668-4668/com.bp5.app W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
10-04 19:15:02.839 4668-4668/com.bp5.app W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
10-04 19:15:02.840 4668-4668/com.bp5.app I/Bp5: MSG.WHAT 103
10-04 19:15:02.841 4668-4668/com.bp5.app I/array: array [{"date":"2016-10-4 19:13:00","highpressure":95,"lowpressure":59,"heartrate":74,"arrhythmia":false,"hsd":false,"dataID":"1EF21B474917AA5FEBCE95540357135A"}]
10-04 19:15:02.841 4668-4668/com.bp5.app W/System.err: org.json.JSONException: No value for wave
10-04 19:15:02.842 4668-4668/com.bp5.app W/System.err:     at org.json.JSONObject.get(JSONObject.java:389)
10-04 19:15:02.842 4668-4668/com.bp5.app W/System.err:     at org.json.JSONObject.getString(JSONObject.java:550)
10-04 19:15:02.842 4668-4668/com.bp5.app W/System.err:     at com.chronicwatch.app.patient.ihealth.BP5$3.handleMessage(BP5.java:480)
10-04 19:15:02.843 4668-4668/com.bp5.app W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-04 19:15:02.843 4668-4668/com.bp5.app W/System.err:     at android.os.Looper.loop(Looper.java:135)
10-04 19:15:02.843 4668-4668/com.bp5.app W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5343)
10-04 19:15:02.843 4668-4668/com.bp5.app W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
10-04 19:15:02.844 4668-4668/com.bp5.app W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
10-04 19:15:02.844 4668-4668/com.bp5.app W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
10-04 19:15:02.844 4668-4668/com.bp5.app W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

**Comment by qqskim** [comment]
Hi

Maybe the problem does not occur in SDK.
The json  which SDK returned does contain the key(“wave"),  but  com.chronicwatch.app.patient.ihealth.BP5 doe  get the key(“wave"), so the exception thrown.

**Comment by manikavi** [comment]
@qqskim ,  Thanks,I got this issue  yesterday,i didn't get this exception before for offline measurement reading.
