### ISSUE TITLE
iHealth SDK crash when onFinish() called

### ISSUE THREAD

**Issue by ipodib** [iHealthDeviceLabs/iHealthDeviceLabs-Android#64]
We a received a strange crash that occurred inside iHealth SDK library. Here is the crash report:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.ihealth.communication.g.d.onScanFinish()' on a null object reference
       at com.ihealth.communication.manager.iHealthDevicesManager$ScanFinishThread.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

#0. Crashed: main: 0 0 0x0000000000000000
       at com.ihealth.communication.manager.iHealthDevicesManager$ScanFinishThread.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

Is there any workaround for this or maybe it's fixed in the last SDK version?

Here are the details about the device where it occurred:
Android Version: 7.0
iHealth SDK: 2.3.2
Device: Samsung S8

**Comment by zhaoyongguang** [comment]
@ipodib 
Thank you for your feedback. This issue is caused by multithreading and we will fix it in the next release.
