### ISSUE TITLE
Crash when disconnecting device

### ISSUE THREAD

**Issue by ipodib** [iHealthDeviceLabs/iHealthDeviceLabs-Android#68]
Hi,

We received a crash from user and we don't know what goes wrong. Here is the stack trace of the crash:

```
Fatal Exception: java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
       at e.d.c.j.run(Unknown Source)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by e.b.f: Attempt to invoke virtual method 'void android.bluetooth.BluetoothGatt.disconnect()' on a null object reference
       at e.d.e.e$a.a(Unknown Source)
       at e.d.e.e$a.call(Unknown Source)
       at e.d.e.b.onError(Unknown Source)
       at e.f.b.a(Unknown Source)
       at e.f.b.onError(Unknown Source)
       at e.d.a.n$a.onError(Unknown Source)
       at e.b.b.a(Unknown Source)
       at e.d.a.n$a.onCompleted(Unknown Source)
       at e.d.a.n$a.onCompleted(Unknown Source)
       at e.f.c.onCompleted(Unknown Source)
       at e.f.d.onCompleted(Unknown Source)
       at e.d.a.bh$c$1.onCompleted(Unknown Source)
       at e.d.a.e.a(Unknown Source)
       at e.d.a.e.call(Unknown Source)
       at e.e.a(Unknown Source)
       at e.d.a.bh$c.a(Unknown Source)
       at e.d.a.bg$1$1.call(Unknown Source)
       at e.d.c.b$a$2.call(Unknown Source)
       at e.d.c.j.run(Unknown Source)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.bluetooth.BluetoothGatt.disconnect()' on a null object reference
       at com.ihealth.communication.b.a.b.b(Unknown Source)
       at com.ihealth.communication.b.a.a.b(Unknown Source)
       at com.ihealth.communication.g.e.a(Unknown Source)
       at {app_id}.disconnect(Unknown Source)
```

Phone model: LG X Style
Android: 6.0
iHealth SDK: 2.3.2

Could you please help with it?

**Comment by jialiabc** [comment]
Hello 
Please update to the latest SDK, please send me sdk@ihealthlabs.com.cn an e-mail with your personal email to get the latest SDK.

**Comment by ipodib** [comment]
@jialiabc I've sent an email.

**Comment by jialiabc** [comment]
Hello ipodib 
Did your issue have been fixed on the latest version ?
