### ISSUE TITLE
SDK Crash that relates to internal SQLite database

### ISSUE THREAD

**Issue by ipodib** [iHealthDeviceLabs/iHealthDeviceLabs-Android#70]
We received a crash report from user that caused by iHealth SDK. Here is the stack trace:

```
Fatal Exception: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 2062)
#################################################################
Error Code : 2062 (SQLITE_CANTOPEN_EMFILE)
Caused By : Application has opened two many files. Maximum of available file descriptors in one process is 1024 in default.
	(unable to open database file (code 2062))
#################################################################
       at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:629)
       at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:323)
       at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:298)
       at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:626)
       at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:537)
       at com.ihealth.communication.d.b.q.a(Unknown Source)
       at com.ihealth.communication.d.b.f.a(Unknown Source)
       at com.ihealth.communication.d.b.ao.run(Unknown Source)
       at java.util.TimerThread.mainLoop(Timer.java:555)
       at java.util.TimerThread.run(Timer.java:505)
```

Phone model: Galaxy S7
Android: 8.0
iHealth SDK: 2.3.5

Can you help with it?

**Comment by zhaoyongguang** [comment]
Hello @ipodib  Which device you are using?

**Comment by ipodib** [comment]
@zhaoyongguang User had paired iHealth Wave and Scales HS4S devices. I don't know exactly which device was connected at the moment but at least one of them.

**Comment by zhaoyongguang** [comment]
@ipodib 
Thank you for your feedback. We will check this and help you solve the problem to ensure normal use.
